#!/bin/bash

# http://www.gnu.org/software/bash/manual/bash.html#The-Set-Builtin
set -o errexit

function setupenvironment()
{
	script="$(readlink --canonicalize "${0}")"
	scriptdir="$(dirname "${script}")"
	scriptname="$(basename "${script}")"
}

setupenvironment "${@}"

cd "${sriptdir}"
forchange bash -c 'compass compile; chromerefresh'
